# Generated by Django 5.0.1 on 2024-06-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasclupt_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='verify',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
