# Generated by Django 5.0.1 on 2024-06-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasclupt_App', '0002_user_data_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
