# Generated by Django 5.0.1 on 2024-06-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasclupt_App', '0003_user_data_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='user_name',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
